### PR TITLE
Refactor docker image creation process

### PR DESCRIPTION
**Pull request by aniruddha2000**
Add makefile to target the makemigrations and migrate

Issue - #7 

To make migrations run -
```bash
docker compose exec backend make migrate
```

Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>

### CODE REVIEW

**Comment by ArkaprabhaChakraborty** [comment]
Does it solve the migration issue? The db remains empty with no schemas defined even after running makemigrations and migrate. Any idea why?

**Comment by aniruddha2000** [comment]
I have tested it locally in my Linux machine and it's totally fine from my side all migrations and schemas are there!

**Comment by ArkaprabhaChakraborty** [comment]
that is because they are literally there in the repo :)

**Comment by aniruddha2000** [comment]
Let's not break things and if some thing is working let's not break it then :)

**Comment by ArkaprabhaChakraborty** [comment]
true that

**Comment by ArkaprabhaChakraborty** [comment]
Tested this.. works like a charm.. let's merge

**Pull request merged**
