### PR TITLE
Add Dockerfile and docker-compose.yaml

### PR DESCRIPTION
**Pull request by aniruddha2000**
Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>

### CODE REVIEW

**Comment by aniruddha2000** [comment]
@ArkaprabhaChakraborty test in a windows machine and give me feedback.

**Comment by ArkaprabhaChakraborty** [comment]
Add docker container setup steps in readme :).

**Comment by aniruddha2000** [comment]
backend breaking with -
```bash
Traceback (most recent call last):
  File "/lms/manage.py", line 22, in <module>
    main()
  File "/lms/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'student'
```

**Comment by ArkaprabhaChakraborty** [comment]
Migrations are needed to be made :)

**Comment by aniruddha2000** [comment]
There is no student app I think that's why it's showing like that

**Pull request merged**
